package oopExercises.goods;

public enum GoodsType {
    SMARTPHONE, COMPUTER, TV_SET, MUSIC_SYSTEM, GAME_CONSOLE, SOFTWARE, WHITE_EQUIPMENT, ACCESSORIES, COSMETICS, CLOTHES, TOY, SPORTS_EQUIPMENT, UNKNOWN;
}
